jaffle_shop:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: vera_demo_suite
      schema: jaffle_shop_dev
      host: e2-demo-field-eng.cloud.databricks.com
      http_path: /sql/1.0/warehouses/862f1d757f0424f7

      # User-to-Machine OAuth authentication
      auth_type: oauth

      threads: 4
      connect_retries: 3
      connect_timeout: 10
      retry_all: true

    prod:
      type: databricks
      catalog: vera_demo_suite
      schema: jaffle_shop_prod
      host: e2-demo-field-eng.cloud.databricks.com
      http_path: /sql/1.0/warehouses/862f1d757f0424f7

      # Machine-to-Machine OAuth authentication
      auth_type: oauth-m2m
      client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}"
      client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}"

      threads: 8
      connect_retries: 3
      connect_timeout: 10
      retry_all: true
